project:
  project_name: 'Graph'
  exp_name: 'exp1'
  seed: 42
  use_wandb: False
  num_workers: 5
  device: 'cuda:0'
data:
  mat_nums: 120
  train_ratio: 0.8
  batch_size: 60
model:
  middle_layer: 2
  use_float: False # float/double
  smoothing_num: 3
  coarse_num: 10
  max_iter: 100
  threshold: 0.0001

train:
  num_epochs: 10
  learning_rate: 0.01
  criterion: 'mse'
  scheduler: 'step'
  step_size: 2 # for step scheduler
  gamma: 0.8 # for step scheduler

