project:
  project_name: 'Graph'
  exp_name: 'exp1'
  seed: 1
  use_wandb: True
  num_workers: 2
  device: 'cuda:0'
data:
  mat_nums: 4
  train_ratio: 0.9
  batch_size: 2
model:
  middle_layer: 4
  use_float: False # float/double
  smoothing_num: 3
  coarse_num: 5
  max_iter: 100
  threshold: 0.0001

train:
  num_epochs: 100
  learning_rate: 0.001
  criterion: 'mse'
  scheduler: 'step'
  step_size: 5 # for step scheduler
  gamma: 0.8 # for step scheduler

